# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_rns <- function(theta, locs, x_covariates, smooth_limits) {
    .Call(`_coco_cov_rns`, theta, locs, x_covariates, smooth_limits)
}

cov_rns_pred <- function(theta, locs, locs_pred, x_covariates, x_covariates_pred, smooth_limits) {
    .Call(`_coco_cov_rns_pred`, theta, locs, locs_pred, x_covariates, x_covariates_pred, smooth_limits)
}

cov_rns_classic <- function(theta, locs, x_covariates) {
    .Call(`_coco_cov_rns_classic`, theta, locs, x_covariates)
}

cov_rns_classic_prod_smooth <- function(theta, locs, x_covariates) {
    .Call(`_coco_cov_rns_classic_prod_smooth`, theta, locs, x_covariates)
}

cov_rns_taper_optimized_predict_range <- function(theta, locs, locs_pred, x_covariates, x_covariates_pred, colindices, rowpointers, smooth_limits) {
    .Call(`_coco_cov_rns_taper_optimized_predict_range`, theta, locs, locs_pred, x_covariates, x_covariates_pred, colindices, rowpointers, smooth_limits)
}

cov_rns_taper_optimized_range <- function(theta, locs, x_covariates, colindices, rowpointers, smooth_limits) {
    .Call(`_coco_cov_rns_taper_optimized_range`, theta, locs, x_covariates, colindices, rowpointers, smooth_limits)
}

